#!/usr/bin/env python3

import logging
import os
import time
from phoenix_framework.server.commander import commander
from phoenix_framework.server.commander.services import start_listeners, start_web
from phoenix_framework.server.utils.config import load_config
from phoenix_framework.server.utils.ui import log
from phoenix_framework.server.args import parser, parse_args

if __name__ == "__main__":
    args = parser.parse_args()
    os.environ["PHOENIX_CONFIG_PATH"] = args.config  # set config path
    config = load_config()
    config = parse_args(args, config)


    log("Welcome to Phoenix Framework.", "success")

    # Initialize commander
    commander = commander()

    # Start listeners
    log("Starting listeners.", "info")
    start_listeners(commander)
    log("All listeners started.", "success")

    # Start the web server
    log("Starting web server.", "info")
    try:
        web_config = config["web"]  # shorten code
        web = start_web(web_config["address"], web_config["port"],
                        web_config["ssl"], commander)
    except Exception as e:
        log(str(e), "danger")
        os._exit(1)
    else:
        log("Web server started.", "success")

    log(f"Accessible at http{'s' if web_config['ssl'] else ''}"
        f"://{web_config['address']}:{web_config['port']}", "info")
    log(f"Press CTRL+C to exit.", "info")
    if args.quiet:
        print("Finished startup.")
    while True:
        try:
            # print(input("Server > "))
            time.sleep(1)
        except KeyboardInterrupt:
            log("Exiting", alert="info")
            os._exit(0)
