#!/usr/bin/python3

import os
# Check if the user is root
if not os.getuid() == 0:
    print("Please start with Sudo or Root Rights")
    exit()
import sys
#sys.path.insert(0, '/usr/share/Phoenix-Framework/')
#os.chdir('/usr/share/Phoenix-Framework/')

try:
    from Utils import *
    import Server as srv
except ImportError:
    print("[ERROR] Not all required Libraries are installed.")
    exit()

if __name__ == "__main__":
    ph_print(logo)

    # Check Database
    try:
        check_db()
    except Exception as e:
        print("[ERROR] " + str(e))
        exit()

    # Get Arguments
    args = srv.parser.parse_args()

    # Initialize Server
    server = srv.Server_Class()

    log("Welcome to Phoenix Framework", "success")
    # Start Listeners
    log("Starting Listeners", "info")
    try:
        srv.start_listeners(server)
    except Exception as e:
        log(str(e), "error")
        exit()
    log("Listeners started", "success")

    # Start the webserver
    log("Starting Web Server", "info")
    try:
        web = srv.start_web(args.address, args.port, args.ssl, server)
        pass
    except Exception as e:
        log(str(e), "error")
        exit()
    else:
        log("Web Server started", "success")

    log(f"Accessible at http{'s' if args.ssl else ''}://{args.address}:{args.port}", "info")
    log(f"Press CTRL+C to exit.", "info")

    while True:
        try:
            time.sleep(1)
        except KeyboardInterrupt:
            log("Exiting", alert="info")
            exit()
        except:
            log("Unknown Error", alert="critical")
            exit()
